// Generated by CoffeeScript 1.6.3
(function() {
  $(function() {
    var updateCSS;
    updateCSS = function(cssText) {
      $('#optional_css').text(cssText);
      return $('#css_edit').val(cssText);
    };
    chrome.storage.sync.get('optional_css', function(result) {
      if (!result.optional_css) {
        return $.when($.get(chrome.extension.getURL("default.css"))).done(function(optional_css) {
          return updateCSS(optional_css);
        });
      } else {
        return updateCSS(result.optional_css);
      }
    });
    $('#update_css').on('click', function(e) {
      var optional_css;
      optional_css = $('#css_edit').val();
      return updateCSS(optional_css);
    });
    chrome.storage.sync.get('pivotal_method', function(result) {
      if (result.pivotal_method) {
        $("input[value=" + result.pivotal_method + "]").click();
      }
      if (result.pivotal_method === 'API') {
        return chrome.storage.sync.get('pivotal_api_key', function(result) {
          if (result.pivotal_api_key) {
            return $("[name='api_key']").val(result.pivotal_api_key);
          }
        });
      }
    });
    $('#toggle_css').on('click', function() {
      return $('#css_edit_block').toggle();
    });
    $('[name="method"]').on('change', function(e) {
      if ($(this).val() === 'API') {
        return $(".api_key_input").show();
      } else {
        return $(".api_key_input").hide();
      }
    });
    return $('#options').on('submit', function(e) {
      e.preventDefault();
      if ($("input[name='method']:checked").length === 0) {
        return;
      }
      switch ($("input[name='method']:checked").val()) {
        case 'API':
          chrome.storage.sync.set({
            'pivotal_method': 'API'
          });
          chrome.storage.sync.set({
            'pivotal_api_key': $("input[name='api_key']").val()
          });
          break;
        case 'DOM':
          $("[name='api_key']").attr('disabled', 'disabled');
          chrome.storage.sync.set({
            'pivotal_method': 'DOM'
          });
          break;
        default:
          return alert('Something went wrong');
      }
      chrome.storage.sync.set({
        "optional_css": $('#css_edit').val()
      });
      $('.notify').fadeIn('fast');
      setTimeout((function() {
        return $('.notify').fadeOut('fast');
      }), 3000);
      return $("[name='api_key']").removeAttr('disabled');
    });
  });

}).call(this);
