// Generated by CoffeeScript 1.6.3
(function() {
  var attachAPIHandlers, attachDOMHandlers;

  attachAPIHandlers = function() {
    var createAPICard;
    createAPICard = function(project_id, id) {
      return chrome.storage.sync.get('pivotal_api_key', function(result) {
        var print_id;
        print_id = "print_story_" + id;
        return $.ajax({
          type: "GET",
          dataType: "xml",
          beforeSend: function(request) {
            return request.setRequestHeader("X-TrackerToken", result.pivotal_api_key);
          },
          url: "https://www.pivotaltracker.com/services/v3/projects/" + project_id + "/stories/" + id,
          success: function(cardInfo, status, xhr) {
            var div, story_points;
            story_points = $(cardInfo).find('estimate').length ? " (" + $(cardInfo).find('estimate').text() + ') ' : '';
            div = Mustache.render($('#story_template').text(), {
              print_id: print_id,
              id: id,
              name: $(cardInfo).find('name').text(),
              story_type: $(cardInfo).find('story_type').text(),
              story_points: story_points
            });
            return $('#print-area').append(div);
          },
          error: function(xhr, error, status) {
            if (status === 'Unauthorized') {
              return alert('Either wrong or absent API key. To fix this, click pivy-print icon');
            } else {
              return alert("Something went wrong. Tell our flying monkeys that. Status: " + status);
            }
          }
        });
      });
    };
    return $(document).on('click', 'header.preview .selector', function(e) {
      var $story, $this, classInfo, id, project_id;
      $this = $(this);
      $story = $this.closest('.story');
      classInfo = $story.attr('class').split(' ');
      project_id = window.location.pathname.match(/projects\/(\d+)/)[1];
      id = ($.grep(classInfo, function(elem) {
        return elem.match(/story_\d+/);
      }))[0].split('_')[1];
      if ($this.hasClass('selected')) {
        return createAPICard(project_id, id);
      } else {
        return $("#print_story_" + id).remove();
      }
    });
  };

  attachDOMHandlers = function() {
    return $(document).on('click', 'header.preview .selector', function(e) {
      var $story, $this, classInfo, div, id, name, points, print_id, story_points, type;
      $this = $(this);
      $story = $this.closest('.story');
      classInfo = $story.attr('class').split(' ');
      id = ($.grep(classInfo, function(elem) {
        return elem.match(/story_\d+/);
      }))[0].split('_')[1];
      type = ($.grep(classInfo, function(elem) {
        return elem.match(/(?:bug)|(?:chore)|(?:feature)/);
      }))[0];
      name = $story.find('.story_name').html();
      story_points = (points = $story.find('.meta').text()) !== '-1' ? "(" + points + ")" : '';
      print_id = "print_story_" + id;
      if ($this.hasClass('selected')) {
        div = Mustache.render($('#story_template').text(), {
          print_id: print_id,
          id: id,
          name: name,
          story_type: type,
          story_points: story_points
        });
        return $('#print-area').append(div);
      } else {
        return $("#" + print_id).remove();
      }
    });
  };

  $(function() {
    $(document).ready(function() {
      $('head').append("<style id='optional_css' type='text/css'></style>");
      $('head').append("<script src='" + (chrome.extension.getURL("js/mustache.js")) + "'></script>");
      $('body').append("<div id='print-area'></div>");
      $('body').append("<script type='text/html' id='story_template'></script>");
      chrome.storage.sync.get('template', function(result) {
        var template;
        if ((template = result.template)) {
          return $('#story_template').text(template);
        } else {
          return $.when($.get(chrome.extension.getURL("default_story.html"))).done(function(response) {
            return $('#story_template').text(response);
          });
        }
      });
      chrome.storage.sync.get('optional_css', function(result) {
        var cssText;
        if ((cssText = result.optional_css)) {
          return $('#optional_css').text(cssText);
        } else {
          return $.when($.get(chrome.extension.getURL("css/default.css"))).done(function(response) {
            return $('#optional_css').text(response);
          });
        }
      });
      chrome.storage.sync.get('pivotal_method', function(result) {
        if (result.pivotal_method === "API") {
          return attachAPIHandlers();
        } else {
          return attachDOMHandlers();
        }
      });
      return $(document).on('click', '.button.stories.menu', function(e) {
        var $this;
        $this = $(this);
        if (!$('#print').length) {
          $this.find('.items').append("<li id='print' class='item'><span class='disabled'>Print</span></li>");
        }
        if ($this.find('.count').length) {
          return $('#print span').removeClass('disabled');
        } else {
          return $('#print span').addClass('disabled');
        }
      });
    });
    return $(document).on('click', '#print', function() {
      if ($(this).find('span').hasClass('disabled')) {
        return;
      }
      return window.print();
    });
  });

}).call(this);
