// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    $(document).ready(function() {
      $('body').append("<div id='print-area'></div>");
      $(document).on('click', 'header.preview .selector', function(e) {
        var $story, $this, classInfo, div, id, print_id, title, type;

        $this = $(this);
        $story = $this.closest('.story');
        classInfo = $story.attr('class').split(' ');
        id = ($.grep(classInfo, function(elem) {
          return elem.match(/story_\d+/);
        }))[0].split('_')[1];
        type = ($.grep(classInfo, function(elem) {
          return elem.match(/(?:bug)|(?:chore)|(?:feature)/);
        }))[0];
        title = $story.find('.story_name').html();
        print_id = "print_story_" + id;
        if ($this.hasClass('selected')) {
          div = "<div id='" + print_id + "' class='card task normal background'><div class='story-identifier'>#" + id + "</div><div class='description'>" + title + "<br></div><div class='tags'>" + type + "</div></div>";
          return $('#print-area').append(div);
        } else {
          return $("#" + print_id).remove();
        }
      });
      return $(document).on('click', '.button.stories.menu', function(e) {
        var $this;

        $this = $(this);
        if (!$('#print').length) {
          $this.find('.items').append("<li id='print' class='item'><span class='disabled'>Print</span></li>");
        }
        if ($this.find('.count').length) {
          return $('#print span').removeClass('disabled');
        } else {
          return $('#print span').addClass('disabled');
        }
      });
    });
    return $(document).on('click', '#print', function() {
      if ($(this).find('span').hasClass('disabled')) {
        return;
      }
      return window.print();
    });
  });

}).call(this);
