// Generated by CoffeeScript 1.6.2
(function() {
  var createCard;

  createCard = function(project_id, id) {
    return chrome.storage.local.get('api_key', function(result) {
      var print_id;

      print_id = "print_story_" + id;
      return $.ajax({
        type: "GET",
        dataType: "xml",
        beforeSend: function(request) {
          return request.setRequestHeader("X-TrackerToken", result.api_key);
        },
        url: "https://www.pivotaltracker.com/services/v3/projects/" + project_id + "/stories/" + id,
        success: function(cardInfo, status, xhr) {
          var div, story_points;

          story_points = $(cardInfo).find('estimate').length ? " (" + $(cardInfo).find('estimate').text() + ') ' : '';
          div = "<div id='" + print_id + "' class='card task normal background'>\n  <div class='story-identifier'>#" + id + "</div>\n  <div class='description'>" + ($(cardInfo).find('name').text()) + "<br></div>\n  <div class='tags'>" + ($(cardInfo).find('story_type').text()) + " " + story_points + " </div>\n</div>";
          return $('#print-area').append(div);
        },
        error: function(xhr, error, status) {
          if (status === 'Unauthorized') {
            return alert('Set your API key. To do so, click pivy-print icon');
          } else {
            return alert("Something went wrong. Tell our flying monkeys that. Status: " + status);
          }
        }
      });
    });
  };

  $(function() {
    $(document).ready(function() {
      $('body').append("<div id='print-area'></div>");
      $(document).on('click', 'header.preview .selector', function(e) {
        var $story, $this, classInfo, id, project_id;

        $this = $(this);
        $story = $this.closest('.story');
        classInfo = $story.attr('class').split(' ');
        project_id = window.location.pathname.match(/projects\/(\d+)/)[1];
        id = ($.grep(classInfo, function(elem) {
          return elem.match(/story_\d+/);
        }))[0].split('_')[1];
        if ($this.hasClass('selected')) {
          return createCard(project_id, id);
        } else {
          return $("#print_story_" + print_id).remove();
        }
      });
      return $(document).on('click', '.button.stories.menu', function(e) {
        var $this;

        $this = $(this);
        if (!$('#print').length) {
          $this.find('.items').append("<li id='print' class='item'><span class='disabled'>Print</span></li>");
        }
        if ($this.find('.count').length) {
          return $('#print span').removeClass('disabled');
        } else {
          return $('#print span').addClass('disabled');
        }
      });
    });
    return $(document).on('click', '#print', function() {
      if ($(this).find('span').hasClass('disabled')) {
        return;
      }
      return window.print();
    });
  });

}).call(this);
