// Generated by CoffeeScript 1.6.2
(function() {
  $(function() {
    var setInput, setReadOnly;

    chrome.storage.local.remove('api_key');
    window.firstTimeText = " <p class='first_time'> \n  We need your API key in order to use the API. To set it, visit \n  <a href=\"https://www.pivotaltracker.com/profile\">your profile page and search \n  for API TOKEN section (bottom of the page)</a> and then copy value to the input below.\n</p>";
    setInput = function(placeholder) {
      return $("#wrapper").html(" <form action='/submit' id='key_form'>\n  <label> Your API KEY IS </label>\n  <input type='text' id='api_key' placeholder='" + placeholder + "'></input>   \n  <input type='submit' value='Set key'>\n</form>");
    };
    setReadOnly = function(value) {
      return $("#wrapper").html(" <form action='/submit' id='key_form'>\n  <label> Your API KEY IS </label>\n  <input disabled readonly type='text' id='api_key' value='" + value + "'></input>   \n  <input type='submit' value='Change key'>\n</form>");
    };
    chrome.storage.onChanged.addListener(function(changes, namespace) {
      return setReadOnly(changes.api_key.newValue);
    });
    chrome.storage.local.get('api_key', function(result) {
      if (!result.api_key) {
        setInput('Your API key goes here');
        $("#key_form").before(firstTimeText);
        return $('#key_form label').remove();
      } else {
        return setReadOnly(result.api_key);
      }
    });
    return $(document).on('submit', '#key_form', function(e) {
      var api_key;

      e.preventDefault();
      switch ($('#key_form [type=submit]').val()) {
        case 'Change key':
          return setInput($('#api_key').val());
        case 'Set key':
          api_key = $('#api_key').val();
          chrome.storage.local.set({
            api_key: api_key
          });
          return setReadOnly(api_key);
      }
    });
  });

}).call(this);
